Repository maismuz/web, pull requests merged in 2025-05, with the labels that each got.

#213 [Fix] Remover pasta de mídia
  .gitignore
  media/imagens_publicacoes/Ceu-Azul.jpg
  media/imagens_publicacoes/Ceu-Azul_nIN3weN.jpg
  requirements.txt
Labels: enhancement

#214 [Feature] Adicionar modelo "Perfil" no app core
  apps/core/admin.py
  apps/core/migrations/0001_initial.py
  apps/core/migrations/__init__.py
  apps/core/models.py
  apps/eventuz/migrations/0001_initial.py
Labels: enhancement

#217 [Fix] Corrigir problemas na aplicação MoveMuz
  apps/movemuz/admin.py
  apps/movemuz/migrations/0001_initial.py
  apps/movemuz/migrations/0002_alter_combustivel_options_alter_tipoveiculo_options_and_more.py
  apps/movemuz/models.py
Labels: enhancement

#219 [Refactor] Resetar as migrações para 0001_initial
  apps/covamuz/migrations/0001_initial.py
  apps/doamuz/migrations/0001_initial.py
  apps/doamuz/migrations/0002_doacao.py
  apps/doamuz/migrations/0003_feedback.py
  apps/doamuz/migrations/0004_feedback_avaliacao.py
  apps/doamuz/migrations/0005_alter_feedback_avaliacao.py
  apps/doamuz/migrations/0006_feedback_tipo_doação.py
  apps/doamuz/migrations/0007_cidade_remove_categoria_cidade_and_more.py
  apps/doamuz/migrations/0008_ongs.py
  apps/doamuz/migrations/0009_alter_ongs_horario_de_funcionamento.py
  apps/eventuz/migrations/0001_initial.py
  apps/eventuz/migrations/0002_categoria_evento_categoria.py
  apps/movemuz/migrations/0001_initial.py
  apps/muzeu/migrations/0001_initial.py
  apps/turismuz/migrations/0001_initial.py
  apps/turismuz/migrations/0002_avaliacao_publicacao.py
  apps/turismuz/migrations/0003_imagempublicacao.py
  apps/turismuz/migrations/0003_publicacao_imagem.py
  apps/turismuz/migrations/0004_merge_0003_imagempublicacao_0003_publicacao_imagem.py
Labels: enhancement

#220 feat/216 implementar gerenciamento de áreas de um cemitério
  apps/covamuz/models.py
Labels: enhancement

#223 [Feature] Adicionar modelo "Denuncia"
  apps/reclamemuz/models.py
Labels: enhancement

#238 [Fix] Corrigir antes de realizar deploy
  apps/core/migrations/0001_initial.py
  apps/covamuz/migrations/0001_initial.py
  apps/covamuz/models.py
  apps/doamuz/migrations/0001_initial.py
  apps/eventuz/migrations/0001_initial.py
  apps/movemuz/migrations/0001_initial.py
  apps/movemuz/migrations/0002_local_viagem.py
  apps/movemuz/migrations/0003_alter_viagem_data_chegada.py
  apps/muzeu/migrations/0001_initial.py
  apps/reclamemuz/migrations/0001_initial.py
  apps/turismuz/migrations/0001_initial.py
Labels: correcao

#239 3rd Pull Request
  .dockerignore
  .github/workflows/image.yaml
  .gitignore
  Dockerfile
  apps/core/admin.py
  apps/core/migrations/0001_initial.py
  apps/core/migrations/__init__.py
  apps/core/models.py
  apps/covamuz/admin.py
  apps/covamuz/migrations/0001_initial.py
  apps/covamuz/models.py
  apps/doamuz/admin.py
  apps/doamuz/migrations/0001_initial.py
  apps/doamuz/models.py
  apps/eventuz/admin.py
  apps/eventuz/migrations/0001_initial.py
  apps/eventuz/models.py
  apps/movemuz/admin.py
  apps/movemuz/migrations/0001_initial.py
  apps/movemuz/models.py
  apps/movemuz/templates/index-movemuz.html
  apps/movemuz/urls.py
  apps/movemuz/views.py
  apps/muzeu/admin.py
  apps/muzeu/migrations/0001_initial.py
  apps/muzeu/models.py
  apps/muzeu/templates/index.html
  apps/muzeu/templates/index_muzeu.html
  apps/muzeu/urls.py
  apps/muzeu/views.py
  apps/reclamemuz/migrations/0001_initial.py
  apps/reclamemuz/models.py
  apps/turismuz/admin.py
  apps/turismuz/apps.py
  apps/turismuz/migrations/0001_initial.py
  apps/turismuz/models.py
  apps/turismuz/templates/components/navbar.html
  apps/turismuz/templates/estabelecimentos.html
  apps/turismuz/templates/guias.html
  apps/turismuz/templates/hometur.html
  apps/turismuz/templates/index.html
  apps/turismuz/templates/publicacao_detail.html
  apps/turismuz/templates/publicacoes.html
  apps/turismuz/urls.py
  apps/turismuz/views.py
  compose.yaml
  config/settings.py
  config/urls.py
  requirements.txt
Labels: melhoria

#243 [Refactor] Atualizar compose
  compose.yaml
Labels: correcao

#244 4th Pull Request
  compose.yaml
Labels: melhoria

#247 [Feature] Adicionar o Gunicorn
  requirements.txt
Labels: melhoria

#249 [Fix] Atualizar o nome dos apps
  apps/contratamuz/apps.py
  apps/covamuz/apps.py
  apps/doamuz/apps.py
  apps/escambuz/apps.py
  apps/esportemuz/apps.py
  apps/eventuz/apps.py
  apps/movemuz/apps.py
  apps/muzeu/apps.py
  apps/muzsaude/apps.py
  apps/reclamemuz/apps.py
  apps/teste/apps.py
Labels: correcao

#251 [Fix] Ajustar allowed hosts e csrf para usar env
  .env_sample
  config/settings.py
Labels: correcao, melhoria

#254 [Fix] Ajustar allowed hosts e csrf para usar env
  .env_sample
  config/settings.py
Labels: correcao, melhoria

#236 Feat/55 Gerenciar tumulos nos cemiterios
  apps/covamuz/admin.py
  apps/covamuz/migrations/0002_areacemiterio_tumulo.py
  apps/covamuz/models.py
Labels: melhoria

#246 Feat/192 forms
  apps/core/static/css/style.css
  apps/core/static/style.css
  apps/core/templates/base_forms.html
  apps/core/templates/homepage.html
  apps/core/templates/index.html
  apps/core/urls.py
  apps/core/views.py
  config/settings.py
Labels: melhoria

#263 feat/59 Gerenciar horários de visitação do cemitério
  apps/core/migrations/0001_initial.py
  apps/core/migrations/__init__.py
  apps/covamuz/admin.py
  apps/covamuz/migrations/0001_initial.py
  apps/covamuz/migrations/0002_areacemiterio_tumulo.py
  apps/covamuz/models.py
  apps/movemuz/migrations/0004_alter_viagem_motorista_passageiro.py
Labels: melhoria

#276 feat: gerenciar pessoas os túmulos
  apps/covamuz/admin.py
  apps/covamuz/models.py
Labels: melhoria

#288 Feat/264 base tabela
  apps/core/static/css/style.css
  apps/core/static/js/table.js
  apps/core/templates/base_forms.html
  apps/core/templates/base_tabela.html
  apps/core/templates/homepage.html
  apps/core/urls.py
  apps/core/views.py
  apps/movemuz/migrations/0002_passageiro.py
Labels: melhoria

#286 Feat/166 gerenciar procedimentos
  apps/adotamuz/admin.py
  apps/adotamuz/migrations/0001_initial.py
  apps/adotamuz/models.py
  requirements.txt
Labels: melhoria

#283 Feat/62 implementar denuncia de irregulares
  apps/escambuz/admin.py
  apps/escambuz/migrations/0001_initial.py
  apps/escambuz/migrations/0002_oferta_denunciairregular_delete_denuncia.py
  apps/escambuz/models.py
Labels: melhoria

#278 Feat/72 gerenciar avaliacoes de usuarios
  apps/escambuz/admin.py
  apps/escambuz/migrations/0001_initial.py
  apps/escambuz/migrations/0002_oferta_denunciairregular_delete_denuncia.py
  apps/escambuz/models.py
Labels: melhoria

#277 Feat/272 configuracoes basicas
  apps/muzsaude/admin.py
  apps/muzsaude/models.py
  apps/muzsaude/static/css/style.css
  apps/muzsaude/static/style.css
  apps/muzsaude/templates/__init__.py
  apps/muzsaude/templates/agendamentos/index.html
  apps/muzsaude/templates/index.html
  apps/muzsaude/urls.py
Labels: melhoria

#229 feat: gerenciar doacao-adocao
  apps/adotamuz/admin.py
  apps/adotamuz/models.py
Labels: melhoria

#231 Feat/68 mensagens entre usuarios
  apps/escambuz/admin.py
  apps/escambuz/models.py
Labels: melhoria

#168 Feat/57 gerenciar pessoas tumulos
  apps/covamuz/admin.py
Labels: melhoria

#203 Feat/58 gerenciar categoria de objeto
  apps/escambuz/admin.py
  apps/escambuz/models.py
  apps/escambuz/templates/index.html
  apps/turismuz/models.py
Labels: melhoria

#298 Feat/58 gerenciar categoria de objeto
  apps/escambuz/admin.py
  apps/escambuz/models.py
  apps/escambuz/templates/index.html
  requirements.txt
Labels: melhoria

#209 Feat/75 visualizar historico de transacao
  apps/escambuz/admin.py
  apps/escambuz/migrations/0001_initial.py
  apps/escambuz/models.py
Labels: melhoria

#294 feat: gerenciar busca de denuncias
  apps/contratamuz/apps.py
  apps/reclamemuz/admin.py
  apps/reclamemuz/models.py
Labels: melhoria

#299 Fix/corrigindo erros de outros apps para executar localmente
  .env_sample
  apps/adotamuz/urls.py
  apps/contratamuz/apps.py
  apps/contratamuz/urls.py
  apps/core/urls.py
  apps/covamuz/admin.py
  apps/covamuz/urls.py
  apps/doamuz/urls.py
  apps/escambuz/urls.py
  apps/esportemuz/apps.py
  apps/esportemuz/migrations/0002_alter_partida_data_hora.py
  apps/esportemuz/migrations/0003_campeonato_encerrado.py
  apps/esportemuz/migrations/0004_classificacao_partidas_jogadas.py
  apps/esportemuz/models.py
  apps/esportemuz/routers.py
  apps/esportemuz/serializers.py
  apps/esportemuz/static/esportemuz/css/style.css
  apps/esportemuz/static/esportemuz/js/script.js
  apps/esportemuz/templates/esportemuz/base.html
  apps/esportemuz/templates/esportemuz/pages/campeonato.html
  apps/esportemuz/templates/esportemuz/pages/equipe.html
  apps/esportemuz/templates/esportemuz/pages/index.html
  apps/esportemuz/templates/esportemuz/partials/footer.html
  apps/esportemuz/templates/esportemuz/partials/navbar.html
  apps/esportemuz/urls.py
  apps/esportemuz/views.py
  apps/esportemuz/viewsets.py
  apps/eventuz/urls.py
  apps/movemuz/admin.py
  apps/movemuz/models.py
  apps/movemuz/urls.py
  apps/muzeu/migrations/0001_initial.py
  apps/muzeu/urls.py
  apps/muzsaude/urls.py
  apps/reclamemuz/urls.py
  apps/teste/urls.py
  apps/turismuz/urls.py
  config/settings.py
Labels: correcao

#327 Feat/51 gerenciar transacao
  apps/escambuz/admin.py
  apps/escambuz/models.py
Labels: melhoria

#332 [Feature] Criação da página inicial
  apps/muzeu/templates/formulario_itens.html
  apps/muzeu/templates/index_muzeu.html
Labels: melhoria

#336 [Feature] Implementando inlines da model patrimonio.
  apps/muzeu/admin.py
Labels: melhoria
